require("opt")
require("keybind")
require("plugin")
require("plugin.neoformat")
require("plugin.rust")
require("plugin.dart")
require("plugin.lualine")

vim.cmd("colorscheme gruvbox")
vim.cmd("syntax enable")
vim.cmd("filetype plugin indent on")
